export const data = [
    {
     "mail": "baris.gunay.pro@gmail.com",
     "lastname": "GUNAY",
     "firstname": "Baris",
     "age": 27,
     "objective": "Freelance dans le développement Web 🙏",
     "hobbies": "Esport \/ Sport \/ Musique \/ Dessin",
     "citation": "\"Le but de l'éducation est de remplir les esprits de façon à les ouvrir.\" mdr ça fait tellement srx, pas d'inspi dsl",
     "instagram": "https:\/\/www.instagram.com\/barisouicestbienmoi\/",
     "linkedin": "https:\/\/www.linkedin.com\/in\/gunay-baris\/",
     "github": "https:\/\/github.com\/BarisRz",
     "photos": "https:\/\/drive.google.com\/open?id=1lrfOd6d1-yaehpxFkmS2JRgNyLMZu-Lc"
    },
    {
     "mail": "baptiste.save79700@gmail.com",
     "lastname": "SAVE",
     "firstname": "Baptiste",
     "age": 24,
     "objective": "Devenir développeur Front-End avec possibilité de formation UI\/UX Designer",
     "hobbies": "UI\/UX Design \/ Créateur de contenu",
     "citation": "Je sais que je ne sais rien - Socrate",
     "facebook": "https:\/\/facebook.com\/Baptiste.Save.79",
     "twitter": "https:\/\/twitter.com\/batsave",
     "instagram": "https:\/\/instagram.com\/batsave__",
     "linkedin": "https:\/\/linkedin.com\/in\/baptiste-save\/",
     "github": "https:\/\/github.com\/Batsave",
     "photos": "https:\/\/drive.google.com\/open?id=1oWYJngBdZ-m-Rog5uvS4SOC4MDA4mACR"
    },
    {
     "mail": "rakotoramangason.elie@gmail.com",
     "lastname": "Rakoto",
     "firstname": "Elie",
     "age": "Secret",
     "objective": "Perso",
     "hobbies": "Perso",
     "citation": "Don't break anyone's heart, they have only one.Break their bones, they have 206.",
     "photos": "https:\/\/drive.google.com\/open?id=1EMZ7JX-7FpAyO2i1w9gIB48iK-G30JII"
    },
    {
     "mail": "francoiscreutzer@gmail.com",
     "lastname": "CREUTZER",
     "firstname": "françois",
     "age": 39,
     "objective": "Devenir Pro du JVS",
     "hobbies": "Musique, Rugby.",
     "citation": "J'adore parler de rien. C'est le seul domaine où j'ai de vagues connaissances.",
     "github": "https:\/\/github.com\/francoiscrtz",
     "photos": "https:\/\/drive.google.com\/open?id=1dxe6KJEA75O9CEwpWnp31qieHo62l-0b"
    },
    {
     "mail": "doriane.leveque2304@gmail.com",
     "lastname": "MULLER LEVEQUE",
     "firstname": "Doriane",
     "age": 30,
     "objective": "Me reconvertir dans un domaine que j'affectionne depuis plusieurs années avec pour ambition de migrer dans une équipe de devs au sein de ma boîte ! :)",
     "hobbies": "Principalement les jeux vidéos, je pourrais y passer plusieurs heures tous les jours .. En dehors de cela, je fais du théâtre amateur et je voue un culte à nos comédiens de doublage français ! :D",
     "citation": "J'en ai énormément mais j'utilise beaucoup celle-ci : \"Il y a baleine sous gravillon !!\"",
     "facebook": "https:\/\/www.facebook.com\/doriane.levequemuller",
     "twitter": "https:\/\/twitter.com\/DorianeML",
     "instagram": "https:\/\/www.instagram.com\/dorianel23\/",
     "linkedin": "https:\/\/www.linkedin.com\/in\/doriane-muller-leveque-898237a9",
     "github": "https:\/\/github.com\/Doriane23",
     "behance": "https:\/\/www.behance.net\/dorianeml",
     "figma": "https:\/\/www.figma.com\/files\/recents-and-sharing\/recently-viewed?fuid=1286695986774059366",
     "photos": "https:\/\/drive.google.com\/open?id=1ImQHFSYu5iGZWN_zzfnomT5hJAtq8kw3"
    },
    {
     "mail": "anthony.gorski@wildcodeschool.com",
     "lastname": "Gorski",
     "firstname": "Anthony",
     "age": 31,
     "objective": "Être comme Benoît ❤️",
     "hobbies": "Échecs, Manga",
     "citation": "Je rigole !",
     "facebook": "#",
     "twitter": "https:\/\/twitter.com\/Gorski_anthony",
     "instagram": "#",
     "linkedin": "https:\/\/www.linkedin.com\/in\/anthony-gorski\/",
     "github": "https:\/\/github.com\/GorskiAnthony",
     "behance": "#",
     "figma": "#",
     "photos": "https:\/\/drive.google.com\/open?id=1EoKbN-aPYUXRoNsnlC0-pRSxluqQlWsm"
    },
    {
     "mail": "tristan.zvunka@gmail.com",
     "lastname": "Zvunka",
     "firstname": "Tristan",
     "age": 30,
     "objective": "Devenir un dev web digne de ce nom!",
     "hobbies": "Musique (MAO, DJing), sport, des bons vins vivants",
     "linkedin": "https:\/\/www.linkedin.com\/in\/tristan-zvunka\/",
     "github": "https:\/\/github.com\/TristanZvunka",
     "photos": "https:\/\/drive.google.com\/open?id=1xk_dYpoSlw9OhRXpqDVgGp8hndRNtSq-"
    }
   ] ;